### PR TITLE
New issue templates

### PR DESCRIPTION
**Pull request by ryanmitchell**
These definitely work ;)

### CODE REVIEW

**Comment by sampoyigi** [comment]
Still not working :)

**Comment by ryanmitchell** [comment]
Only works on public repos - this definitely worked for me. When you view either of the files in GitHub web does it give an error?

**Comment by sampoyigi** [comment]
No error... I tried a new issue on the TastyIgniter repo after merging and no changes at all. Just the blank issue textarea.

**Comment by ryanmitchell** [comment]
Just applied them here - https://github.com/ryanmitchell/ti-ext-kitchendisplay/issues/new/choose <https://github.com/ryanmitchell/ti-ext-kitchendisplay/issues/new/choose> - they seem to work?

See: https://github.com/ryanmitchell/ti-ext-kitchendisplay/tree/master/.github/ISSUE_TEMPLATE

**Pull request merged**
